languageCode = "en-us"
title = "Mike Perham"
baseURL = "https://www.mikeperham.com"
theme = "mini"
relativeURLs = false
publishDir = "docs"
disableKinds = ["section", "taxonomy"]
pygmentsCodefences = true
pygmentsStyle = "monokai"
rssLimit = 10

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  description = "Ruby, OSS and the Internet"
  shortDescription = "Ruby, OSS and the Internet"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "960px"
  customDateFormat = "2006-01-02"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"
  author = "Mike Perham"
  email = "mike@perham.net"
  github = "mperham"
